/**
 * Owner-controlled DMCA / takedown draft generator.
 * Never auto-submits to platforms — owner copies and sends.
 */

export interface DmcaDraftInput {
  ownerShortId?: string | null;
  certificateId?: string | null;
  dnaRecordId?: string | null;
  filename?: string | null;
  matchUrl?: string | null;
  matchType?: string | null;
  similarity?: number | null;
  riskLevel?: string | null;
  discoveredAt?: string | null;
  notes?: string | null;
}

export function buildDmcaDraft(input: DmcaDraftInput): string {
  const when = input.discoveredAt
    ? new Date(input.discoveredAt).toUTCString()
    : new Date().toUTCString();

  return [
    'PINIT HUB — TAKEDOWN / COPYRIGHT NOTICE DRAFT',
    '============================================',
    '',
    'This draft is generated for the asset owner to review and submit.',
    'Pinit HUB does not auto-send this notice to any platform.',
    '',
    `Date (UTC): ${when}`,
    `Owner Pinit ID: ${input.ownerShortId || 'N/A'}`,
    `Certificate ID: ${input.certificateId || 'N/A'}`,
    `Protection / DNA Record ID: ${input.dnaRecordId || 'N/A'}`,
    `Original filename: ${input.filename || 'N/A'}`,
    '',
    'INFRINGING / DUPLICATE LOCATION',
    `URL / source: ${input.matchUrl || 'Not provided — attach evidence URL'}`,
    `Match type: ${input.matchType || 'N/A'}`,
    `Similarity: ${input.similarity != null ? `${Math.round(input.similarity * (input.similarity <= 1 ? 100 : 1))}%` : 'N/A'}`,
    `Risk: ${input.riskLevel || 'N/A'}`,
    '',
    'STATEMENT',
    'I am the owner (or authorized agent) of the original protected work identified above.',
    'I have a good-faith belief that the material at the listed location is unauthorized.',
    'I request removal or disablement of access to the infringing material.',
    '',
    input.notes ? `Additional notes:\n${input.notes}\n` : '',
    'Generated by Pinit HUB — for owner use only.',
  ]
    .filter(Boolean)
    .join('\n');
}

export function downloadDmcaDraft(input: DmcaDraftInput, filename = 'pinit-takedown-draft.txt'): void {
  const text = buildDmcaDraft(input);
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
