-- Exchange licensed-asset sharing, tracked in Hub.
--
-- HAND-WRITTEN, NOT generated by `prisma migrate dev`.
-- Prisma's generated diff also proposes `DROP TABLE "spatial_auth_packages"`,
-- because that table exists in the database but is absent from schema.prisma
-- (pre-existing drift). Dropping it would destroy live DNA data, so this
-- migration deliberately contains ONLY the additive changes for this feature.
-- Reconcile that drift separately before running any generated migration.

-- Exchange lifecycle events on the canonical Asset timeline.
-- ADD VALUE is additive and safe; IF NOT EXISTS keeps it idempotent.
ALTER TYPE "AssetTimelineType" ADD VALUE IF NOT EXISTS 'LISTED';
ALTER TYPE "AssetTimelineType" ADD VALUE IF NOT EXISTS 'SOLD';
ALTER TYPE "AssetTimelineType" ADD VALUE IF NOT EXISTS 'SHARED';
ALTER TYPE "AssetTimelineType" ADD VALUE IF NOT EXISTS 'SHARE_VIEWED';
ALTER TYPE "AssetTimelineType" ADD VALUE IF NOT EXISTS 'SHARE_DOWNLOADED';

-- Link a share to the canonical Asset and to the Exchange license that
-- authorised it. All nullable / defaulted — existing rows are unaffected.
ALTER TABLE "share_links" ADD COLUMN IF NOT EXISTS "assetId" TEXT;
ALTER TABLE "share_links" ADD COLUMN IF NOT EXISTS "exchangeOrderId" TEXT;
ALTER TABLE "share_links" ADD COLUMN IF NOT EXISTS "exchangeSealId" TEXT;
ALTER TABLE "share_links" ADD COLUMN IF NOT EXISTS "licenseTier" TEXT;
ALTER TABLE "share_links" ADD COLUMN IF NOT EXISTS "sourceContext" TEXT NOT NULL DEFAULT 'hub';

CREATE INDEX IF NOT EXISTS "share_links_assetId_idx" ON "share_links"("assetId");
CREATE INDEX IF NOT EXISTS "share_links_exchangeSealId_idx" ON "share_links"("exchangeSealId");
