"""
Production authenticity ensemble — multi-engine weighted fusion.

Engines:
  • Metadata (EXIF / AI markers / camera hints)
  • Pixel forensics (ELA, double-JPEG hint, edge/texture)
  • AI classifier (CLIP zero-shot + EfficientNet-B7 texture signal via timm)
  • Frequency domain (FFT radial energy / DCT HF ratio)
  • PRNU / noise fingerprint (block noise inconsistency)
  • Deepfake / edit heuristics (delegates to deepfake_service)

Weights (user spec):
  15% metadata | 20% pixel | 20% AI classifier | 15% frequency
  10% PRNU | 10% edit/ELA | 10% semantic (CLIP margin)
"""
from __future__ import annotations

import base64
import io
import re
from typing import Any

import numpy as np
from PIL import Image

from ..base import EnterpriseAIService, ServiceResult

try:
    from ..semantic_embeddings import semantic_embeddings_service
except ImportError:
    semantic_embeddings_service = None

try:
    from ..deepfake import deepfake_service
except ImportError:
    deepfake_service = None

AI_MARKERS = [
    "midjourney", "dall-e", "dalle", "stable diffusion", "stablediffusion",
    "openai", "firefly", "leonardo", "ideogram", "imagen", "flux", "aigc",
    "c2pa", "contentcredentials", "synthetic", "generated by ai",
]
CAMERA_RE = re.compile(
    r"(canon|nikon|sony|apple|iphone|samsung|google|pixel|fujifilm|dji|gopro)",
    re.I,
)

WEIGHTS = {
    "metadata": 0.15,
    "pixel": 0.20,
    "ai_classifier": 0.20,
    "frequency": 0.15,
    "prnu": 0.10,
    "edit": 0.10,
    "semantic": 0.10,
}


def _clamp(n: float, lo: float = 0.0, hi: float = 100.0) -> float:
    return float(max(lo, min(hi, n)))


class AuthenticityEnsembleService(EnterpriseAIService):
    name = "authenticity_ensemble"
    _effnet = None
    _effnet_preprocess = None

    def is_available(self) -> bool:
        try:
            import cv2  # noqa: F401
            from PIL import Image  # noqa: F401
        except ImportError:
            return False
        return True

    def status(self) -> dict[str, Any]:
        return {
            "module": self.name,
            "available": self.is_available(),
            "capabilities": [
                "metadata_analysis",
                "ela",
                "fft_frequency",
                "prnu_noise",
                "clip_zero_shot_ai",
                "efficientnet_texture",
                "weighted_ensemble",
                "suspicion_heatmap",
            ],
            "weights": WEIGHTS,
            "efficientnetAvailable": self._effnet_available(),
        }

    def _effnet_available(self) -> bool:
        try:
            import timm  # noqa: F401
            import torch  # noqa: F401
            return True
        except ImportError:
            return False

    def _ensure_effnet(self) -> bool:
        if self._effnet is not None:
            return True
        if not self._effnet_available():
            return False
        try:
            import timm
            import torch

            self._effnet = timm.create_model(
                "efficientnet_b7",
                pretrained=True,
                num_classes=0,
            )
            self._effnet.eval()
            cfg = timm.data.resolve_model_data_config(self._effnet)
            self._effnet_preprocess = timm.data.create_transform(**cfg, is_training=False)
            if torch.cuda.is_available():
                self._effnet = self._effnet.cuda()
            return True
        except Exception:
            self._effnet = None
            return False

    def _decode(self, image_bytes: bytes, max_dim: int = 1024) -> tuple[np.ndarray, np.ndarray] | None:
        try:
            img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
            w, h = img.size
            scale = min(1.0, max_dim / max(w, h))
            if scale < 1.0:
                img = img.resize((int(w * scale), int(h * scale)), Image.Resampling.LANCZOS)
            rgb = np.array(img)
            import cv2

            gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
            return rgb, gray
        except Exception:
            return None

    def _metadata_score(self, image_bytes: bytes, filename: str) -> tuple[float, list[str], dict[str, Any]]:
        hay = (image_bytes[: min(len(image_bytes), 512_000)] + filename.encode("latin1", "ignore")).decode(
            "latin1", "ignore"
        ).lower()
        score = 0.0
        reasons: list[str] = []
        marker = next((m for m in AI_MARKERS if m in hay), None)
        has_camera = bool(CAMERA_RE.search(hay))
        if marker:
            score = 88.0
            reasons.append(f'AI/generative marker "{marker}" in file container')
        # Missing EXIF alone is NOT an AI signal (WhatsApp/email/Windows often strip it)
        if has_camera:
            score = max(0.0, score - 30.0)
            reasons.append("Camera/device string detected — lowers pure-AI likelihood")
        return _clamp(score), reasons, {"marker": marker, "hasCameraHint": has_camera}

    def _ela_score(self, rgb: np.ndarray) -> tuple[float, float, list[str]]:
        import cv2

        pil = Image.fromarray(rgb)
        buf = io.BytesIO()
        pil.save(buf, format="JPEG", quality=90)
        recompressed = np.array(Image.open(io.BytesIO(buf.getvalue())).convert("RGB"))
        diff = cv2.absdiff(rgb, recompressed)
        gray = cv2.cvtColor(diff, cv2.COLOR_RGB2GRAY)
        ela_mean = float(gray.mean()) / 255.0
        reasons: list[str] = []
        edit_score = 0.0
        ai_freq_score = 0.0
        if ela_mean > 0.12:
            edit_score = _clamp(ela_mean * 180)
            reasons.append(f"ELA recompression residual elevated ({ela_mean:.3f}) — possible edit")
        # Clean ELA alone is common on lightly compressed camera JPEGs — do not treat as AI
        return edit_score, ai_freq_score, reasons

    def _fft_score(self, gray: np.ndarray) -> tuple[float, list[str]]:
        import cv2

        small = cv2.resize(gray, (256, 256), interpolation=cv2.INTER_AREA).astype(np.float32)
        f = np.fft.fftshift(np.fft.fft2(small))
        mag = np.log1p(np.abs(f))
        h, w = mag.shape
        cy, cx = h // 2, w // 2
        y, x = np.ogrid[:h, :w]
        dist = np.sqrt((x - cx) ** 2 + (y - cy) ** 2)
        inner = mag[dist < min(h, w) * 0.15].mean()
        outer = mag[dist > min(h, w) * 0.35].mean()
        ratio = float(outer / max(inner, 1e-6))
        reasons: list[str] = []
        score = 0.0
        # Diffusion outputs: steeper HF drop vs camera photos
        if ratio < 0.55:
            score = _clamp((0.55 - ratio) * 180)
            reasons.append(f"FFT HF energy drop ({ratio:.2f}) consistent with generative smoothing")
        elif ratio > 1.8:
            score = 25.0
            reasons.append(f"FFT spectrum ratio ({ratio:.2f}) suggests heavy recompression")
        return score, reasons

    def _prnu_score(self, gray: np.ndarray) -> tuple[float, list[str]]:
        import cv2

        h, w = gray.shape[:2]
        if h < 64 or w < 64:
            return 0.0, []
        bs = 32
        stds: list[float] = []
        for y in range(0, h - bs, bs):
            for x in range(0, w - bs, bs):
                patch = gray[y : y + bs, x : x + bs].astype(np.float32)
                residual = patch - cv2.GaussianBlur(patch, (5, 5), 0)
                stds.append(float(residual.std()))
        if len(stds) < 4:
            return 0.0, []
        arr = np.array(stds)
        cv_noise = float(arr.std() / max(arr.mean(), 1e-6))
        reasons: list[str] = []
        score = 0.0
        if cv_noise < 0.20:
            score = _clamp((0.20 - cv_noise) * 280)
            reasons.append(f"Uniform PRNU/noise floor (CV {cv_noise:.2f}) — weak camera sensor fingerprint")
        elif cv_noise > 0.75:
            score = 30.0
            reasons.append(f"Irregular noise blocks (CV {cv_noise:.2f}) — possible regional tampering")
        return score, reasons

    def _effnet_texture_score(self, rgb: np.ndarray) -> tuple[float, list[str], str]:
        if not self._ensure_effnet():
            return 0.0, [], "UNAVAILABLE"
        try:
            import torch

            pil = Image.fromarray(rgb)
            tensor = self._effnet_preprocess(pil).unsqueeze(0)
            if torch.cuda.is_available():
                tensor = tensor.cuda()
            with torch.no_grad():
                feats = self._effnet(tensor)
                vec = feats[0].cpu().numpy()
            kurt = float(np.mean((vec - vec.mean()) ** 4) / (vec.std() ** 4 + 1e-6))
            sparsity = float(np.mean(np.abs(vec) < 0.05))
            score = 0.0
            reasons: list[str] = []
            if kurt < 2.5 and sparsity > 0.35:
                score = 48.0
                reasons.append(
                    f"EfficientNet-B7 embedding kurtosis {kurt:.2f} — texture lacks natural photo sharpness"
                )
            return score, reasons, "COMPLETE"
        except Exception as exc:
            return 0.0, [str(exc)], "FAILED"

    def _heatmap_png_b64(self, gray: np.ndarray, block: int = 32) -> str | None:
        try:
            import cv2

            h, w = gray.shape[:2]
            grid_h = max(1, h // block)
            grid_w = max(1, w // block)
            heat = np.zeros((grid_h, grid_w), dtype=np.float32)
            for gy in range(grid_h):
                for gx in range(grid_w):
                    y0, x0 = gy * block, gx * block
                    patch = gray[y0 : y0 + block, x0 : x0 + block]
                    if patch.size < 16:
                        continue
                    lap = cv2.Laplacian(patch, cv2.CV_64F)
                    heat[gy, gx] = max(0.0, 8.0 - float(np.abs(lap).mean()))
            if heat.max() > 0:
                heat = heat / heat.max()
            heat_u8 = (heat * 255).astype(np.uint8)
            heat_color = cv2.applyColorMap(
                cv2.resize(heat_u8, (w, h), interpolation=cv2.INTER_NEAREST),
                cv2.COLORMAP_JET,
            )
            overlay = cv2.addWeighted(cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR), 0.55, heat_color, 0.45, 0)
            ok, buf = cv2.imencode(".png", overlay)
            if not ok:
                return None
            return base64.b64encode(buf.tobytes()).decode("ascii")
        except Exception:
            return None

    def analyze(self, image_bytes: bytes, mime_type: str = "", filename: str = "") -> ServiceResult:
        if not self.is_available():
            return ServiceResult(False, {}, "OpenCV unavailable", self.name)
        if mime_type and not mime_type.startswith("image/"):
            return ServiceResult(True, {
                "skipped": True,
                "reason": "Non-image media",
            }, "OK", self.name)

        decoded = self._decode(image_bytes)
        if decoded is None:
            return ServiceResult(False, {}, "Could not decode image", self.name)
        rgb, gray = decoded

        engines: list[dict[str, Any]] = []
        evidence: list[dict[str, Any]] = []
        all_reasons: list[str] = []

        meta_score, meta_reasons, meta_sig = self._metadata_score(image_bytes, filename)
        engines.append({
            "id": "metadata",
            "name": "Metadata Engine",
            "status": "COMPLETE",
            "score": meta_score,
            "summary": meta_reasons[0] if meta_reasons else "Metadata scan complete",
            "findings": meta_reasons,
        })
        all_reasons.extend(meta_reasons)

        edit_ela, ai_ela, ela_reasons = self._ela_score(rgb)
        fft_score, fft_reasons = self._fft_score(gray)
        prnu_score, prnu_reasons = self._prnu_score(gray)
        pixel_score = _clamp(max(ai_ela * 0.6, edit_ela * 0.8))
        engines.append({
            "id": "pixel-forensics",
            "name": "Pixel Forensics (ELA)",
            "status": "COMPLETE",
            "score": pixel_score,
            "summary": "; ".join(ela_reasons[:2]) or "ELA complete",
            "findings": ela_reasons,
        })
        all_reasons.extend(ela_reasons)

        engines.append({
            "id": "frequency",
            "name": "Frequency Analysis (FFT)",
            "status": "COMPLETE",
            "score": fft_score,
            "summary": fft_reasons[0] if fft_reasons else "FFT spectrum nominal",
            "findings": fft_reasons,
        })
        all_reasons.extend(fft_reasons)

        engines.append({
            "id": "prnu",
            "name": "NoisePrint / PRNU",
            "status": "COMPLETE",
            "score": prnu_score,
            "summary": prnu_reasons[0] if prnu_reasons else "Sensor noise within normal range",
            "findings": prnu_reasons,
        })
        all_reasons.extend(prnu_reasons)

        clip_score = 0.0
        clip_reasons: list[str] = []
        clip_status = "UNAVAILABLE"
        if semantic_embeddings_service and semantic_embeddings_service.is_available():
            clip_res = semantic_embeddings_service.classify_ai_generation(image_bytes)
            if clip_res.success:
                clip_status = "COMPLETE"
                clip_score = float(clip_res.data.get("generatedConfidencePercent", 0) or 0)
                clip_reasons.append(
                    f'CLIP zero-shot AI likelihood {clip_score:.1f}% (top: {clip_res.data.get("topPrompt")})'
                )
                all_reasons.extend(clip_reasons)
        engines.append({
            "id": "clip-ai",
            "name": "CLIP AI Classifier",
            "status": clip_status,
            "score": clip_score,
            "summary": clip_reasons[0] if clip_reasons else "CLIP unavailable",
            "findings": clip_reasons,
        })

        eff_score, eff_reasons, eff_status = self._effnet_texture_score(rgb)
        engines.append({
            "id": "efficientnet-b7",
            "name": "EfficientNet-B7 Texture",
            "status": eff_status,
            "score": eff_score,
            "summary": eff_reasons[0] if eff_reasons else "Texture signal nominal",
            "findings": eff_reasons,
        })
        all_reasons.extend(eff_reasons)

        ai_classifier_score = _clamp(clip_score * 0.72 + eff_score * 0.28)

        deepfake_score = 0.0
        edit_score = edit_ela
        if deepfake_service and deepfake_service.is_available():
            df = deepfake_service.analyze(image_bytes, mime_type or "image/jpeg")
            if df.success:
                deepfake_score = float(df.data.get("generatedConfidencePercent", 0) or 0)
                edit_score = max(edit_score, float(df.data.get("confidencePercent", 0) or 0) * 0.7)
                if df.data.get("reasons"):
                    all_reasons.extend(df.data["reasons"][:3])

        # Weighted ensemble — CLIP / EfficientNet dominate generative decision
        ai_probability = (
            WEIGHTS["metadata"] * meta_score
            + WEIGHTS["pixel"] * pixel_score
            + WEIGHTS["ai_classifier"] * ai_classifier_score
            + WEIGHTS["frequency"] * fft_score
            + WEIGHTS["prnu"] * prnu_score
            + WEIGHTS["edit"] * (edit_score * 0.35)  # edit ≠ AI-generation
            + WEIGHTS["semantic"] * clip_score
        )
        ai_probability = _clamp(ai_probability)

        # Confusion-matrix gate: high AI needs classifier agreement (CLIP or marker)
        classifier_agrees = clip_score >= 48 or bool(meta_sig.get("marker")) or eff_score >= 55
        if ai_probability >= 52 and not classifier_agrees:
            ai_probability = _clamp(ai_probability * 0.45)

        # Tamper only from real edit/ELA/PRNU-regional evidence — not missing EXIF
        tamper_score = 0.0
        if edit_ela >= 40:
            tamper_score = max(tamper_score, edit_ela * 0.85)
        if prnu_score >= 45 and "regional" in " ".join(prnu_reasons).lower():
            tamper_score = max(tamper_score, prnu_score * 0.55)
        if fft_score >= 40 and "recompression" in " ".join(fft_reasons).lower():
            tamper_score = max(tamper_score, 28.0)
        tamper_score = _clamp(tamper_score)

        authenticity_score = _clamp(100 - max(ai_probability * 0.75, tamper_score * 0.6))

        verdict = "UNKNOWN"
        if meta_sig.get("marker") or (ai_probability >= 72 and classifier_agrees):
            verdict = "AI_GENERATED"
        elif ai_probability >= 55 and classifier_agrees:
            verdict = "LIKELY_AI"
        elif tamper_score >= 55 and edit_ela >= 45:
            verdict = "TAMPERED"
        elif edit_ela >= 50 and tamper_score >= 40:
            verdict = "EDITED"
        elif authenticity_score >= 65 and ai_probability < 40 and tamper_score < 35:
            verdict = "ORIGINAL"
        elif ai_probability < 35 and tamper_score < 30:
            verdict = "ORIGINAL"
        else:
            verdict = "SUSPICIOUS"

        confidence = 0.45
        if verdict == "AI_GENERATED":
            confidence = min(0.92, 0.55 + ai_probability / 200)
        elif verdict == "LIKELY_AI":
            confidence = min(0.78, 0.5 + ai_probability / 200)
        elif verdict == "ORIGINAL":
            confidence = min(0.88, 0.55 + authenticity_score / 200)
        elif verdict in ("TAMPERED", "EDITED"):
            confidence = min(0.82, 0.5 + tamper_score / 200)

        heatmap_b64 = self._heatmap_png_b64(gray)

        for eng in engines:
            if eng.get("findings"):
                for i, finding in enumerate(eng["findings"][:3]):
                    evidence.append({
                        "id": f"{eng['id']}-{i}",
                        "engine": eng["id"],
                        "severity": "high" if (eng.get("score") or 0) >= 65 else "medium" if (eng.get("score") or 0) >= 40 else "info",
                        "title": eng["name"],
                        "detail": finding,
                        "scoreImpact": round((eng.get("score") or 0) * WEIGHTS.get(eng["id"].split("-")[0], 0.1)),
                    })

        return ServiceResult(True, {
            "version": "ensemble-v1",
            "verdict": verdict,
            "aiProbability": round(ai_probability, 1),
            "tamperScore": round(tamper_score, 1),
            "authenticityScore": round(authenticity_score, 1),
            "confidence": round(confidence, 3),
            "confidenceLevel": "HIGH" if confidence >= 0.75 else "MEDIUM" if confidence >= 0.55 else "LOW",
            "aiGenerated": ai_probability >= 58,
            "aiGeneratedConfidence": round(ai_probability / 100, 4),
            "generatedConfidencePercent": round(ai_probability, 1),
            "engines": engines,
            "evidence": evidence[:24],
            "reasons": all_reasons[:16],
            "weights": WEIGHTS,
            "heatmapPngBase64": heatmap_b64,
            "signals": {
                "metadataScore": meta_score,
                "pixelScore": pixel_score,
                "clipScore": clip_score,
                "efficientNetScore": eff_score,
                "fftScore": fft_score,
                "prnuScore": prnu_score,
                "editScore": edit_score,
                "marker": meta_sig.get("marker"),
            },
        }, "OK", self.name)


authenticity_ensemble_service = AuthenticityEnsembleService()
