import { useState } from 'react';
import { Search, Database, RefreshCw, Eye, GitCompare, ChevronDown, ChevronUp, Share2, Cpu } from 'lucide-react';
import { API_BASE_URL } from '../config/api.config';
import { format } from 'date-fns';
import { useApi, formatBytes } from '../hooks/useApi';
import { listDnaRecords, deriveFileType, api } from '../services/dashboard.api';
import { SkeletonTable } from '../components/ui/Skeleton';
import { EmptyState } from '../components/ui/EmptyState';
import { Badge, ClassificationBadge, FileTypeBadge } from '../components/ui/Badge';
import { Modal } from '../components/ui/Modal';
import type { DnaRecord } from '../types/dashboard.types';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

function DnaDetailModal({ record, onClose }: { record: DnaRecord; onClose: () => void }) {
  const { user } = useAuth();
  return (
    <Modal open title="DNA Record Details" onClose={onClose} size="lg">
      <div className="p-6 space-y-3">
        <div className="grid grid-cols-2 gap-3">
          {[
            { label: 'DNA Record ID',   value: record.id,                mono: true,  accent: true },
            { label: 'Status',          value: record.status,            mono: false, accent: false, badge: true },
            { label: 'File',            value: record.imageFilename,     mono: false, accent: false },
            { label: 'MIME Type',       value: record.imageMimeType,     mono: true,  accent: false },
            { label: 'File Size',       value: formatBytes(record.imageSizeBytes), mono: true, accent: false },
            { label: 'File Type',       value: deriveFileType(record), mono: false, accent: false, typeBadge: true },
            { label: 'Engine Version',  value: record.engineVersion ?? '1.0.0', mono: true, accent: false },
            { label: 'Schema Version',  value: record.schemaVersion,    mono: true,  accent: false },
            { label: 'Created At',      value: format(new Date(record.createdAt), 'PPpp'), mono: false, accent: false },
            { label: 'Owner User ID',   value: user?.shortId ?? '—', mono: true, accent: true },
            { label: 'Vault ID',        value: record.vaultId ?? 'Not vaulted', mono: true, accent: !!record.vaultId },
          ].map(row => (
            <div key={row.label} className="bg-bg-elevated rounded-lg p-3">
              <p className="text-2xs text-gray-500 mono mb-1">{row.label}</p>
              {'badge' in row && row.badge
                ? <ClassificationBadge value={record.status} />
                : 'typeBadge' in row && row.typeBadge
                ? <FileTypeBadge type={deriveFileType(record)} />
                : <p className={`text-xs break-all ${row.mono ? 'mono' : ''} ${row.accent ? 'text-dna-400' : 'text-gray-200'}`}>
                    {row.value as string}
                  </p>
              }
            </div>
          ))}
        </div>

        <div className="rounded-xl bg-dna-500/5 border border-dna-500/20 p-4">
          <p className="text-xs font-semibold text-dna-400 mb-1">DNA Fingerprint</p>
          <p className="text-2xs text-gray-400">
            This record contains a 6-layer cryptographic fingerprint generated by the Universal DNA Engine.
            Each layer uses a different algorithm to capture a unique aspect of the file's identity.
          </p>
        </div>
      </div>
    </Modal>
  );
}

type SortField = 'createdAt' | 'imageFilename' | 'fileType' | 'status';

export function DnaRecordsPage() {
  const { data: records, loading, error, refetch } = useApi(listDnaRecords);
  const [search, setSearch]     = useState('');
  const [filter, setFilter]     = useState('ALL');
  const [sort, setSort]         = useState<SortField>('createdAt');
  const [asc, setAsc]           = useState(false);
  const [selected, setSelected] = useState<DnaRecord | null>(null);
  const [aiMode, setAiMode]     = useState(false);
  const [aiResults, setAiResults] = useState<string[]>([]); // dnaRecordIds
  const [aiSearching, setAiSearching] = useState(false);
  const navigate = useNavigate();

  const handleSearch = async (q: string) => {
    setSearch(q);
    if (!aiMode || !q.trim()) { setAiResults([]); return; }
    setAiSearching(true);
    try {
      const { data } = await api.post(`${API_BASE_URL}/ai/search`, {
        query: q.trim(), topK: 20, threshold: 0.30, mode: 'hybrid',
      });
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const payload: any = (data as any).data ?? data;
      setAiResults((payload.results ?? []).map((r: { dnaRecordId: string }) => r.dnaRecordId));
    } catch {
      setAiResults([]);
    } finally {
      setAiSearching(false);
    }
  };

  const filtered = (records ?? [])
    .filter(r => {
      const matchesFilter = filter === 'ALL' || deriveFileType(r) === filter || r.status === filter;
      if (!matchesFilter) return false;
      if (!search) return true;
      const keyword = (
        r.imageFilename.toLowerCase().includes(search.toLowerCase()) ||
        r.id.toLowerCase().includes(search.toLowerCase())
      );
      if (aiMode && !aiSearching) {
        return aiResults.length > 0 ? aiResults.includes(r.id) : keyword;
      }
      return keyword;
    })
    .sort((a, b) => {
      let va: string, vb: string;
      if (sort === 'createdAt') { va = a.createdAt; vb = b.createdAt; }
      else if (sort === 'imageFilename') { va = a.imageFilename; vb = b.imageFilename; }
      else if (sort === 'fileType') { va = deriveFileType(a); vb = deriveFileType(b); }
      else { va = a.status; vb = b.status; }
      return asc ? va.localeCompare(vb) : vb.localeCompare(va);
    });

  const toggleSort = (field: SortField) => {
    if (sort === field) setAsc(!asc);
    else { setSort(field); setAsc(false); }
  };

  const SortIcon = ({ field }: { field: SortField }) =>
    sort === field
      ? (asc ? <ChevronUp size={12} /> : <ChevronDown size={12} />)
      : null;

  const uniqueTypes = [...new Set((records ?? []).map(r => deriveFileType(r)))];
  const fileTypes = ['ALL', ...uniqueTypes];
  const statuses  = ['COMPLETE', 'PARTIAL', 'FAILED'];

  if (error) return (
    <div className="flex items-center justify-center h-64 text-center">
      <div>
        <p className="text-danger text-sm mb-3">{error}</p>
        <button onClick={refetch} className="btn btn-secondary btn-sm"><RefreshCw size={13} /> Retry</button>
      </div>
    </div>
  );

  return (
    <div className="space-y-5 animate-fade-in">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-xl font-bold text-white">DNA Records</h1>
          <p className="text-sm text-gray-500 mt-0.5">All generated fingerprint records</p>
        </div>
        <div className="flex items-center gap-2">
          {!loading && records && <Badge variant="dna">{records.length} records</Badge>}
          <button onClick={refetch} disabled={loading} className="btn btn-secondary btn-sm">
            <RefreshCw size={13} className={loading ? 'animate-spin' : ''} />
          </button>
        </div>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-2 flex-wrap">
        {/* Status filters */}
        {['ALL', ...statuses].map(s => (
          <button
            key={s}
            onClick={() => setFilter(s)}
            className={`text-xs px-3 py-1.5 rounded-full border transition-all ${
              filter === s
                ? 'bg-dna-500/20 border-dna-500/40 text-dna-400'
                : 'border-bg-border text-gray-500 hover:text-white hover:border-gray-600'
            }`}
          >
            {s}
          </button>
        ))}
        <div className="h-4 w-px bg-bg-border mx-1" />
        {fileTypes.slice(1).map(t => (
          <button
            key={t}
            onClick={() => setFilter(t)}
            className={`text-xs px-3 py-1.5 rounded-full border transition-all ${
              filter === t
                ? 'bg-dna-500/20 border-dna-500/40 text-dna-400'
                : 'border-bg-border text-gray-500 hover:text-white hover:border-gray-600'
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      {/* Table */}
      <div className="card overflow-hidden p-0">
        <div className="flex items-center gap-3 p-4 border-b border-bg-border">
          <div className="relative flex-1">
            {aiSearching
              ? <RefreshCw size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-dna-400 animate-spin" />
              : <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-500" />}
            <input
              type="text"
              placeholder={aiMode ? 'Search by meaning, content, or filename…' : 'Search by filename or DNA Record ID…'}
              value={search}
              onChange={e => handleSearch(e.target.value)}
              className="input pl-9 text-sm"
            />
          </div>
          <button
            onClick={() => { setAiMode(m => !m); setSearch(''); setAiResults([]); }}
            title={aiMode ? 'Switch to keyword search' : 'Switch to AI semantic search'}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all shrink-0 ${
              aiMode
                ? 'bg-dna-500/20 border-dna-500/40 text-dna-400'
                : 'border-bg-border text-gray-500 hover:text-white hover:border-gray-600'
            }`}
          >
            <Cpu size={13} />
            {aiMode ? 'AI Search ON' : 'AI Search'}
          </button>
        </div>

        <div className="overflow-x-auto">
          <table className="data-table">
            <thead>
              <tr>
                <th>
                  <button onClick={() => toggleSort('imageFilename')} className="flex items-center gap-1 hover:text-white">
                    File <SortIcon field="imageFilename" />
                  </button>
                </th>
                <th>
                  <button onClick={() => toggleSort('fileType')} className="flex items-center gap-1 hover:text-white">
                    Type <SortIcon field="fileType" />
                  </button>
                </th>
                <th>DNA Record ID</th>
                <th>
                  <button onClick={() => toggleSort('status')} className="flex items-center gap-1 hover:text-white">
                    Status <SortIcon field="status" />
                  </button>
                </th>
                <th>Vault</th>
                <th>
                  <button onClick={() => toggleSort('createdAt')} className="flex items-center gap-1 hover:text-white">
                    Created <SortIcon field="createdAt" />
                  </button>
                </th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <SkeletonTable rows={6} />
              ) : filtered.length === 0 ? (
                <tr><td colSpan={7}>
                  <EmptyState
                    icon={Database}
                    title="No DNA records"
                    description="Generate a DNA fingerprint to see records here"
                  />
                </td></tr>
              ) : (
                filtered.map(r => (
                  <tr key={r.id} className="cursor-pointer" onClick={() => setSelected(r)}>
                    <td>
                      <p className="text-sm font-medium text-white truncate max-w-[200px]">{r.imageFilename}</p>
                      <p className="text-2xs text-gray-500 mono">{formatBytes(r.imageSizeBytes)}</p>
                    </td>
                    <td><FileTypeBadge type={deriveFileType(r)} /></td>
                    <td><span className="mono text-2xs text-dna-400">{r.id.slice(0, 12)}…</span></td>
                    <td><ClassificationBadge value={r.status} /></td>
                    <td>
                      {r.vaultId
                        ? <Badge variant="success" dot>Vaulted</Badge>
                        : <Badge variant="muted">Not vaulted</Badge>}
                    </td>
                    <td className="text-xs text-gray-400">
                      {format(new Date(r.createdAt), 'MMM d, yyyy')}
                    </td>
                    <td onClick={e => e.stopPropagation()}>
                      <div className="flex items-center gap-1">
                        <button
                          onClick={() => setSelected(r)}
                          className="btn-ghost btn-icon text-gray-500 hover:text-white"
                          title="View"
                        >
                          <Eye size={14} />
                        </button>
                        <button
                          onClick={() => navigate('/compare')}
                          className="btn-ghost btn-icon text-gray-500 hover:text-cyan"
                          title="Compare"
                        >
                          <GitCompare size={14} />
                        </button>
                        <button
                          onClick={() => navigate(`/chain/${r.id}`)}
                          className="btn-ghost btn-icon text-gray-500 hover:text-dna-400"
                          title="View Propagation Chain"
                        >
                          <Share2 size={14} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        {filtered.length > 0 && (
          <div className="flex items-center justify-between px-4 py-3 border-t border-bg-border">
            <p className="text-xs text-gray-500">Showing {filtered.length} of {records?.length ?? 0} records</p>
          </div>
        )}
      </div>

      {selected && <DnaDetailModal record={selected} onClose={() => setSelected(null)} />}
    </div>
  );
}
