/**
 * AI-generation signal engine — decoded-pixel + container heuristics.
 * Complements L11 (which previously scored compressed bytes, not pixels).
 */
import sharp from 'sharp';
import type { AuthenticityEngineResult, AuthenticityEvidence } from './authenticity.types';

const AI_MARKERS = [
  'midjourney', 'dall-e', 'dalle', 'openai', 'stable diffusion', 'stablediffusion',
  'automatic1111', 'comfyui', 'firefly', 'adobe firefly', 'leonardo.ai', 'leonardoai',
  'ideogram', 'imagen', 'flux.1', 'flux1', 'black forest', 'synthetic', 'aigc',
  'c2pa', 'contentcredentials', 'content credentials', 'generated by ai',
  'this image was created with', 'dreamstudio', 'runwayml', 'runway ml',
  'novelai', 'bing image creator', 'gpt-4o', 'chatgpt',
];

export interface AiGenerationProbe {
  score: number;
  likelyAiGenerated: boolean;
  reasons: string[];
  evidence: AuthenticityEvidence[];
  engine: AuthenticityEngineResult;
  hasCameraExif: boolean;
  markerHit: string | null;
}

function clampPct(n: number): number {
  if (!Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(100, Math.round(n)));
}

function stdDev(vals: number[]): number {
  if (vals.length < 2) return 0;
  const mean = vals.reduce((a, b) => a + b, 0) / vals.length;
  const v = vals.reduce((a, b) => a + (b - mean) ** 2, 0) / vals.length;
  return Math.sqrt(v);
}

/** Scan container bytes / filename for generative-AI markers (XMP, PNG tEXt, C2PA). */
export function scanAiContainerMarkers(buffer: Buffer, filename: string): string | null {
  const hay = Buffer.concat([buffer.subarray(0, Math.min(buffer.length, 512_000)), Buffer.from(filename)])
    .toString('latin1')
    .toLowerCase();
  for (const m of AI_MARKERS) {
    if (hay.includes(m)) return m;
  }
  return null;
}

/**
 * Decode pixels and score generative-AI likelihood (0–100).
 * Real camera photos: natural sensor noise, EXIF make/model, irregular textures.
 * Diffusion/GAN exports: often missing camera EXIF, overly smooth HF energy, uniform local noise.
 */
export async function probeAiGeneration(
  buffer: Buffer,
  mimeType: string,
  filename: string,
): Promise<AiGenerationProbe> {
  const evidence: AuthenticityEvidence[] = [];
  const reasons: string[] = [];
  let score = 0;
  let hasCameraExif = false;
  const markerHit = scanAiContainerMarkers(buffer, filename);

  if (!mimeType.startsWith('image/')) {
    return {
      score: 0,
      likelyAiGenerated: false,
      reasons: [],
      evidence: [],
      hasCameraExif: false,
      markerHit: null,
      engine: {
        id: 'ai-generation',
        name: 'AI Generated Detection',
        status: 'SKIPPED',
        summary: 'Applies to images',
      },
    };
  }

  if (markerHit) {
    score = Math.max(score, 82);
    reasons.push(`AI / generative marker in file: "${markerHit}"`);
    evidence.push({
      id: 'ai-marker',
      engine: 'ai-generation',
      severity: 'critical',
      title: 'Generative AI marker found',
      detail: `Container/filename contains "${markerHit}" — strong AI-generation signal.`,
      scoreImpact: 35,
    });
  }

  try {
    const img = sharp(buffer, { failOn: 'none' });
    const meta = await img.metadata();
    const exifBuf = meta.exif ?? Buffer.alloc(0);
    const exifLatin = exifBuf.toString('latin1');
    // Camera Make/Model ASCII often appears in EXIF IFD
    hasCameraExif = /(?:Canon|Nikon|Sony|Apple|iPhone|Samsung|Google|Pixel|Huawei|Xiaomi|OnePlus|Fujifilm|Olympus|Panasonic|Leica|DJI|GoPro)/i.test(exifLatin)
      || /\x00Make\x00|\x00Model\x00/.test(exifLatin);

    const noExif = !meta.exif || meta.exif.length < 32;
    const w = meta.width ?? 0;
    const h = meta.height ?? 0;
    const megapixels = (w * h) / 1_000_000;
    const looksPhotographicSize = megapixels >= 0.3 && w >= 512 && h >= 512;

    if (noExif && looksPhotographicSize && !hasCameraExif) {
      // Info only — WhatsApp / email / OS often strip EXIF from real camera photos
      evidence.push({
        id: 'ai-no-camera-exif',
        engine: 'ai-generation',
        severity: 'info',
        title: 'No camera EXIF on photo-sized image',
        detail: `${w}×${h} with little/no EXIF — not decisive alone (common after messaging apps or scrubbing).`,
        scoreImpact: 0,
      });
    } else if (hasCameraExif) {
      score = Math.max(0, score - 25);
      evidence.push({
        id: 'ai-camera-present',
        engine: 'ai-generation',
        severity: 'info',
        title: 'Camera device metadata present',
        detail: 'EXIF suggests a capture device — lowers pure AI-generation likelihood.',
      });
    }

    // Decode downscaled luminance for frequency / noise stats
    const { data, info } = await img
      .rotate()
      .resize(256, 256, { fit: 'inside', withoutEnlargement: true })
      .greyscale()
      .raw()
      .toBuffer({ resolveWithObject: true });

    const width = info.width;
    const height = info.height;
    const pixels = new Uint8Array(data);
    const n = width * height;
    if (n < 64) {
      throw new Error('Image too small for AI probe');
    }

    // Laplacian-ish high-frequency energy (4-neighbour)
    let lapSum = 0;
    let lapSq = 0;
    let lapCount = 0;
    for (let y = 1; y < height - 1; y++) {
      for (let x = 1; x < width - 1; x++) {
        const i = y * width + x;
        const c = pixels[i]!;
        const lap = Math.abs(
          4 * c - pixels[i - 1]! - pixels[i + 1]! - pixels[i - width]! - pixels[i + width]!,
        );
        lapSum += lap;
        lapSq += lap * lap;
        lapCount++;
      }
    }
    const lapMean = lapSum / Math.max(1, lapCount);
    const lapVar = lapSq / Math.max(1, lapCount) - lapMean * lapMean;

    // Local noise std across 32×32 blocks
    const blockStds: number[] = [];
    const bs = 32;
    for (let y = 0; y + bs <= height; y += bs) {
      for (let x = 0; x + bs <= width; x += bs) {
        const vals: number[] = [];
        for (let by = 0; by < bs; by++) {
          for (let bx = 0; bx < bs; bx++) {
            vals.push(pixels[(y + by) * width + (x + bx)]!);
          }
        }
        // high-pass residual within block
        const mean = vals.reduce((a, b) => a + b, 0) / vals.length;
        const residuals = vals.map((v) => Math.abs(v - mean));
        blockStds.push(stdDev(residuals));
      }
    }
    const noiseMean = blockStds.length ? blockStds.reduce((a, b) => a + b, 0) / blockStds.length : 0;
    const noiseSpread = stdDev(blockStds);
    const noiseCv = noiseMean > 0.01 ? noiseSpread / noiseMean : 0;

    // Oversmooth HF → strong diffusion fingerprint
    if (lapMean < 8 && looksPhotographicSize) {
      score += 28;
      reasons.push(`Abnormally smooth high-frequency detail (edge energy ${lapMean.toFixed(1)})`);
      evidence.push({
        id: 'ai-smooth-hf',
        engine: 'ai-generation',
        severity: 'high',
        title: 'Synthetic smoothness (frequency)',
        detail: `Mean edge energy ${lapMean.toFixed(1)} is lower than typical camera photos — common in diffusion outputs.`,
        scoreImpact: 18,
      });
    } else if (lapMean < 14 && looksPhotographicSize) {
      score += 14;
      reasons.push(`Low high-frequency texture (edge energy ${lapMean.toFixed(1)})`);
      evidence.push({
        id: 'ai-low-hf',
        engine: 'ai-generation',
        severity: 'medium',
        title: 'Low texture detail',
        detail: `Edge energy ${lapMean.toFixed(1)} is on the low side for natural photography.`,
        scoreImpact: 8,
      });
    }

    // Very uniform local noise (AI often has flat noise floor)
    if (noiseCv < 0.18 && noiseMean > 1 && looksPhotographicSize) {
      score += 18;
      reasons.push(`Unusually uniform local noise (CV ${noiseCv.toFixed(2)})`);
      evidence.push({
        id: 'ai-uniform-noise',
        engine: 'ai-generation',
        severity: 'medium',
        title: 'Uniform sensor-noise pattern',
        detail: `Local noise coefficient of variation ${noiseCv.toFixed(2)} — camera PRNU is usually more irregular.`,
        scoreImpact: 10,
      });
    }

    // Extremely low Laplacian variance with decent size
    if (lapVar < 40 && looksPhotographicSize) {
      score += 12;
      reasons.push('Low Laplacian variance (plastic / synthetic look)');
      evidence.push({
        id: 'ai-lap-var',
        engine: 'ai-generation',
        severity: 'medium',
        title: 'Plastic / synthetic texture variance',
        detail: `Laplacian variance ${lapVar.toFixed(1)} is low for organic photo texture.`,
        scoreImpact: 8,
      });
    }

    // PNG photographic without camera — often Midjourney / SD export
    const isPng = meta.format === 'png' && (mimeType === 'image/png' || mimeType === 'image/x-png');
    if (isPng && looksPhotographicSize && !hasCameraExif) {
      score += 16;
      reasons.push('Photo-like PNG without camera metadata (common AI export)');
      evidence.push({
        id: 'ai-png-photo',
        engine: 'ai-generation',
        severity: 'medium',
        title: 'Photo-like PNG export',
        detail: 'Large PNG without camera EXIF is a frequent Stable Diffusion / Midjourney export pattern.',
        scoreImpact: 10,
      });
    }

    // Square SD/Midjourney export sizes (512, 768, 1024, 1280, …)
    const side = Math.min(w, h);
    const isSquare = w > 0 && h > 0 && Math.abs(w - h) <= Math.max(4, Math.round(Math.min(w, h) * 0.01));
    const aiSquareSizes = new Set([512, 768, 1024, 1280, 1536, 2048]);
    if (isSquare && aiSquareSizes.has(side) && !hasCameraExif) {
      score += 14;
      reasons.push(`Square ${w}×${h} export — common generative-AI output resolution`);
      evidence.push({
        id: 'ai-square-res',
        engine: 'ai-generation',
        severity: 'medium',
        title: 'Generative-AI square resolution',
        detail: `${w}×${h} square without camera EXIF matches common diffusion export sizes.`,
        scoreImpact: 10,
      });
    }

    // Composite: multiple weak signals together are stronger than any single detector
    const signalCount = reasons.length;
    if (signalCount >= 3 && score >= 28) {
      score = clampPct(Math.max(score, 55));
      reasons.push(`Composite: ${signalCount} independent AI-generation indicators aligned`);
    } else if (signalCount >= 2 && score >= 32 && noExif && !hasCameraExif) {
      score = clampPct(Math.max(score, 50));
      reasons.push('Composite: missing camera metadata + export-pattern signals');
    }

    score = clampPct(score);
    const likelyAiGenerated = score >= 48 || !!markerHit || (signalCount >= 3 && score >= 40);

    if (likelyAiGenerated) {
      evidence.push({
        id: 'ai-verdict-hint',
        engine: 'ai-generation',
        severity: score >= 65 ? 'high' : 'medium',
        title: score >= 65 ? 'Likely AI-generated' : 'Possible AI-generated',
        detail: `AI-generation probe score ${score}/100. ${reasons.slice(0, 2).join('; ') || 'Multiple weak signals combined.'}`,
        scoreImpact: score >= 65 ? 22 : 12,
      });
    } else {
      evidence.push({
        id: 'ai-clear',
        engine: 'ai-generation',
        severity: 'info',
        title: 'No strong AI-generation fingerprint',
        detail: `AI-generation probe score ${score}/100 — below likely-AI threshold.`,
      });
    }

    return {
      score,
      likelyAiGenerated,
      reasons,
      evidence,
      hasCameraExif,
      markerHit,
      engine: {
        id: 'ai-generation',
        name: 'AI Generated Detection',
        status: 'COMPLETE',
        summary: likelyAiGenerated
          ? `Likely AI-generated (score ${score}/100)`
          : `No strong generative fingerprint (score ${score}/100)`,
        score,
        findings: reasons.length ? reasons : ['No strong generative-AI markers'],
      },
    };
  } catch (err) {
    // Marker-only fallback
    const scoreOnly = markerHit ? 82 : 0;
    return {
      score: scoreOnly,
      likelyAiGenerated: !!markerHit,
      reasons: markerHit ? [`AI marker: ${markerHit}`] : [],
      evidence,
      hasCameraExif,
      markerHit,
      engine: {
        id: 'ai-generation',
        name: 'AI Generated Detection',
        status: markerHit ? 'PARTIAL' : 'FAILED',
        summary: markerHit
          ? `Marker hit "${markerHit}" (pixel probe failed)`
          : (err instanceof Error ? err.message : 'AI probe failed'),
        score: scoreOnly,
      },
    };
  }
}
