/**
 * PINIT-DNA — Professional Report Generator (Phase 4.2)
 *
 * Generates downloadable forensic reports in PDF, JSON, and CSV.
 * Uses jsPDF client-side — zero server dependency.
 * DOES NOT modify any existing logic.
 */

import type { ComparisonResult, VaultRecord, DnaRecord } from '../types/dashboard.types';
import type { AuthUser } from '../lib/auth';
import { classifyTampering, explainLayer } from './forensic-analysis';
import { formatBytes } from '../hooks/useApi';

// ─── Report metadata ──────────────────────────────────────────────────────────

function reportId(): string {
  return 'RPT-' + Date.now().toString(36).toUpperCase();
}

function ts(): string {
  return new Date().toISOString();
}

// ─── JSON export (already partially in Reports page, enhanced here) ───────────

export function exportComparisonJSON(result: ComparisonResult): void {
  const classification = classifyTampering(result);
  const report = {
    reportId:          reportId(),
    reportType:        'DNA_COMPARISON_FORENSIC_REPORT',
    generatedAt:       ts(),
    engineVersion:     '2.0.0-universal',
    pinit_dna_version: '2.0',
    comparison: {
      comparisonId:         result.comparisonId,
      classification:       result.classification,
      overallConfidence:    result.overallConfidenceScore,
      tamperingDetected:    result.tamperingDetected,
      sameFileType:         result.sameFileType,
      processingMs:         result.processingMs,
      comparedAt:           result.comparedAt,
    },
    files: {
      fileA: result.fileA,
      fileB: result.fileB,
    },
    tamperingAnalysis: {
      primaryClass:    classification.primaryClass,
      allClasses:      classification.classes,
      severity:        classification.severity,
      explanation:     classification.explanation,
      technicalDetail: classification.technicalDetail,
    },
    layers: result.layerComparisons.map(l => ({
      ...l,
      explanation: explainLayer(l),
    })),
    indicators: result.forensicReport.tamperingIndicators,
    recommendation: result.forensicReport.recommendation,
    methodology:    result.forensicReport.methodology,
    legalDisclaimer: 'This report is generated by PINIT-DNA Universal File DNA Engine. ' +
                     'The cryptographic fingerprints are mathematically verifiable. ' +
                     'For legal proceedings, independent verification is recommended.',
  };

  downloadJSON(report, `forensic-report-${result.comparisonId.slice(0, 8)}.json`);
}

export function exportDNACertificateJSON(vault: VaultRecord, user?: AuthUser): void {
  const certId = `CERT-DNA-${vault.id.slice(0, 8).toUpperCase()}`;
  const cert = {
    reportId:        reportId(),
    certificateId:   certId,
    reportType:      'DNA_OWNERSHIP_CERTIFICATE',
    generatedAt:     ts(),
    issuedBy:        'PINIT-DNA Universal File DNA Engine v2.0',
    owner: {
      userId:    user?.sub    ?? 'unknown',
      shortId:   user?.shortId ?? 'unknown',
      name:      user?.name   ?? 'unknown',
    },
    subject: {
      fileName:      vault.originalFileName,
      mimeType:      vault.originalMimeType,
      originalSize:  vault.originalSizeBytes,
    },
    identity: {
      dnaRecordId:   vault.dnaRecordId,
      vaultId:       vault.id,
      registeredAt:  vault.createdAt,
    },
    security: {
      encryptionAlgorithm: vault.encryptionAlgorithm,
      keyDerivation:       vault.keyDerivation,
      dnaLayers:           10,
    },
    legalStatement:
      `This certificate confirms that the file "${vault.originalFileName}" was registered ` +
      `in the PINIT-DNA system on ${new Date(vault.createdAt).toLocaleDateString()} ` +
      `by user ${user?.name ?? user?.shortId ?? 'unknown'} (ID: ${user?.sub ?? 'unknown'}). ` +
      `The file has been cryptographically fingerprinted across 10 independent layers ` +
      `and securely stored with AES-256-GCM encryption.`,
  };
  downloadJSON(cert, `${certId}.json`);
}

// ─── CSV export ────────────────────────────────────────────────────────────────

export function exportComparisonCSV(result: ComparisonResult): void {
  const classification = classifyTampering(result);

  const headers = ['Layer', 'Name', 'Algorithm', 'Similarity %', 'Status', 'Changed', 'Description'];
  const rows = result.layerComparisons.map(l => [
    `L${l.layer}`,
    l.name,
    l.implementation,
    `${l.similarityPercent}%`,
    l.matched ? 'PASS' : 'FAIL',
    l.changed ? 'YES' : 'NO',
    `"${l.changeDescription.replace(/"/g, '""')}"`,
  ]);

  const meta = [
    ['Report ID', reportId()],
    ['Generated At', ts()],
    ['File A', result.fileA.filename],
    ['File B', result.fileB.filename],
    ['Classification', result.classification],
    ['Confidence Score', `${result.overallConfidenceScore}%`],
    ['Tampering Detected', result.tamperingDetected ? 'YES' : 'NO'],
    ['Tampering Class', classification.primaryClass],
    ['Severity', classification.severity],
    ['Recommendation', `"${result.forensicReport.recommendation.replace(/"/g, '""')}"`],
    [],
    ['=== LAYER ANALYSIS ==='],
  ];

  const csv = [
    ...meta.map(r => r.join(',')),
    headers.join(','),
    ...rows.map(r => r.join(',')),
    [],
    ['=== TAMPERING INDICATORS ==='],
    ['Layer', 'Severity', 'Description', 'Evidence'],
    ...result.forensicReport.tamperingIndicators.map(t => [
      t.layerName, t.severity,
      `"${t.description.replace(/"/g, '""')}"`,
      `"${t.evidence.replace(/"/g, '""')}"`,
    ].join(',')),
  ].join('\n');

  downloadText(csv, `forensic-report-${result.comparisonId.slice(0, 8)}.csv`, 'text/csv');
}

export function exportDNARecordsCSV(records: DnaRecord[]): void {
  const headers = ['DNA Record ID', 'Filename', 'File Type', 'MIME Type', 'Size (bytes)', 'Status', 'Vaulted', 'Created At'];
  const rows = records.map(r => [
    r.id,
    `"${r.imageFilename}"`,
    r.fileType ?? 'IMAGE',
    r.imageMimeType,
    r.imageSizeBytes,
    r.status,
    r.vaultId ? 'YES' : 'NO',
    r.createdAt,
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  downloadText(csv, `dna-records-export-${Date.now()}.csv`, 'text/csv');
}

// ─── PDF export using jsPDF ────────────────────────────────────────────────────

export async function exportComparisonPDF(result: ComparisonResult): Promise<void> {
  // Dynamic import to keep bundle lean
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const classification = classifyTampering(result);
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210; const MARGIN = 14;
  let y = 0;

  // ── Cover stripe ──────────────────────────────────────────────────────────
  doc.setFillColor(22, 33, 62);
  doc.rect(0, 0, W, 40, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PINIT-DNA', MARGIN, 16);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Universal File DNA Forensic Report', MARGIN, 23);
  doc.text(`Generated: ${new Date().toLocaleString()}`, MARGIN, 30);
  doc.text(`Report ID: ${reportId()}`, MARGIN, 37);

  // Classification badge colour
  const clsColor: Record<string, [number,number,number]> = {
    DNA_MATCH: [16, 185, 129], SIMILAR: [245, 158, 11], DIFFERENT: [239, 68, 68],
  };
  const [cr,cg,cb] = clsColor[result.classification] ?? [100,100,100];
  doc.setFillColor(cr, cg, cb);
  doc.roundedRect(W - 60, 8, 46, 14, 3, 3, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(255,255,255);
  doc.text(result.classification.replace('_', ' '), W - 37, 17, { align: 'center' });

  y = 50;
  doc.setTextColor(30, 30, 30);

  // ── Section: Summary ──────────────────────────────────────────────────────
  sectionHeader(doc, 'EXECUTIVE SUMMARY', y); y += 8;

  const summaryRows = [
    ['Overall Confidence', `${result.overallConfidenceScore}%`],
    ['Classification', result.classification.replace('_', ' ')],
    ['Tampering Detected', result.tamperingDetected ? 'YES — See indicators below' : 'No tampering detected'],
    ['Tampering Class', classification.primaryClass],
    ['Severity Level', classification.severity],
    ['Same File Type', result.sameFileType ? 'Yes' : 'No (cross-type comparison)'],
    ['Processing Time', `${result.processingMs}ms`],
    ['Compared At', new Date(result.comparedAt).toLocaleString()],
  ];

  autoTable(doc, {
    startY: y, head: [], body: summaryRows, margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 9, cellPadding: 3 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50, fillColor: [240, 242, 248] }, 1: { cellWidth: 120 } },
    theme: 'plain',
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Section: Files ────────────────────────────────────────────────────────
  sectionHeader(doc, 'FILE COMPARISON', y); y += 8;
  autoTable(doc, {
    startY: y,
    head: [['', 'File A — Original', 'File B — Comparison']],
    body: [
      ['Filename', result.fileA.filename, result.fileB.filename],
      ['File Type', result.fileA.fileType, result.fileB.fileType],
      ['MIME Type', result.fileA.mimeType, result.fileB.mimeType],
      ['Size', `${Math.round(result.fileA.sizeBytes / 1024)} KB`, `${Math.round(result.fileB.sizeBytes / 1024)} KB`],
    ],
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 9 },
    headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' },
    columnStyles: { 0: { fontStyle: 'bold', fillColor: [240, 242, 248], cellWidth: 40 } },
    theme: 'striped',
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Section: DNA Layer Analysis ───────────────────────────────────────────
  sectionHeader(doc, 'DNA LAYER-BY-LAYER ANALYSIS', y); y += 8;
  const layerRows = result.layerComparisons.map(l => {
    const exp = explainLayer(l);
    return [
      `L${l.layer} · ${exp.name}`,
      `${l.similarityPercent}%`,
      l.matched ? 'PASS' : 'FAIL',
      l.changed ? 'YES' : 'NO',
      exp.shortStatus,
    ];
  });
  autoTable(doc, {
    startY: y,
    head: [['Layer', 'Similarity', 'Status', 'Changed', 'Assessment']],
    body: layerRows,
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 9 },
    headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: 'bold' },
    didParseCell: (data) => {
      if (data.column.index === 2 && data.section === 'body') {
        const val = data.cell.raw as string;
        data.cell.styles.textColor = val === 'PASS' ? [16,185,129] : [239,68,68];
        data.cell.styles.fontStyle = 'bold';
      }
    },
    theme: 'striped',
  });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 8;

  // ── Section: Tampering Indicators ────────────────────────────────────────
  if (result.forensicReport.tamperingIndicators.length > 0) {
    if (y > 230) { doc.addPage(); y = 20; }
    sectionHeader(doc, 'TAMPERING INDICATORS', y); y += 8;
    autoTable(doc, {
      startY: y,
      head: [['Severity', 'Layer', 'Description']],
      body: result.forensicReport.tamperingIndicators.map(t => [
        t.severity, t.layerName, t.description,
      ]),
      margin: { left: MARGIN, right: MARGIN },
      styles: { fontSize: 9 },
      headStyles: { fillColor: [127, 29, 29], textColor: 255, fontStyle: 'bold' },
      theme: 'striped',
    });
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  y = (doc as any).lastAutoTable.finalY + 8;
  }

  // ── Section: Recommendation ───────────────────────────────────────────────
  if (y > 240) { doc.addPage(); y = 20; }
  sectionHeader(doc, 'FORENSIC RECOMMENDATION', y); y += 8;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const lines = doc.splitTextToSize(result.forensicReport.recommendation, W - MARGIN * 2);
  doc.text(lines, MARGIN, y);
  y += lines.length * 5 + 8;

  // ── Section: Methodology ─────────────────────────────────────────────────
  sectionHeader(doc, 'METHODOLOGY', y); y += 8;
  const mLines = doc.splitTextToSize(result.forensicReport.methodology, W - MARGIN * 2);
  doc.text(mLines, MARGIN, y);
  y += mLines.length * 5 + 8;

  // ── Footer ────────────────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`PINIT-DNA Universal File DNA Engine v2.0 · Confidential Forensic Report · Page ${i}/${pageCount}`, W / 2, 292, { align: 'center' });
  }

  doc.save(`forensic-report-${result.comparisonId.slice(0, 8)}.pdf`);
}

// ─── Certificate PDF ───────────────────────────────────────────────────────────

export async function exportCertificatePDF(vault: VaultRecord, user?: AuthUser): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const certId = `CERT-DNA-${vault.id.slice(0, 8).toUpperCase()}`;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210; const MARGIN = 20;

  // Background
  doc.setFillColor(8, 11, 20);
  doc.rect(0, 0, W, 297, 'F');

  // Border
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(1.5);
  doc.rect(10, 10, W - 20, 277);

  // Top stripe
  doc.setFillColor(22, 33, 100);
  doc.rect(10, 10, W - 20, 30, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18); doc.setFont('helvetica', 'bold');
  doc.text('PINIT-DNA', W / 2, 26, { align: 'center' });
  doc.setFontSize(10); doc.setFont('helvetica', 'normal');
  doc.text('Universal File DNA Ownership Certificate', W / 2, 34, { align: 'center' });

  // Certificate ID
  doc.setFontSize(11); doc.setFont('helvetica', 'bold');
  doc.setTextColor(148, 130, 240);
  doc.text(certId, W / 2, 52, { align: 'center' });

  // Verified badge
  doc.setFillColor(16, 185, 129);
  doc.roundedRect(W / 2 - 25, 56, 50, 10, 3, 3, 'F');
  doc.setTextColor(255, 255, 255); doc.setFontSize(9);
  doc.text('VERIFIED', W / 2, 63, { align: 'center' });

  let y = 78;
  const field = (label: string, value: string) => {
    doc.setFontSize(8); doc.setTextColor(100, 120, 150); doc.setFont('helvetica', 'normal');
    doc.text(label.toUpperCase(), MARGIN, y);
    doc.setFontSize(10); doc.setTextColor(220, 225, 235); doc.setFont('helvetica', 'bold');
    doc.text(value, MARGIN, y + 5);
    y += 14;
  };

  const sectionDivider = (title: string) => {
    y += 2;
    doc.setFillColor(22, 33, 100);
    doc.rect(MARGIN, y, W - MARGIN * 2, 7, 'F');
    doc.setFontSize(8); doc.setFont('helvetica', 'bold');
    doc.setTextColor(148, 130, 240);
    doc.text(title, MARGIN + 2, y + 5);
    y += 12;
  };

  // ── Owner Section ───────────────────────────────────────────────────────────
  sectionDivider('OWNER INFORMATION');
  field('Owner Name',    user?.name    ?? 'Unknown');
  field('Owner ID',      user?.sub     ?? 'Unknown');
  field('Short ID',      user?.shortId ?? 'Unknown');

  // ── File Section ────────────────────────────────────────────────────────────
  sectionDivider('FILE INFORMATION');
  field('Registered File',  vault.originalFileName);
  field('MIME Type',        vault.originalMimeType);
  field('Original Size',    formatBytes(vault.originalSizeBytes));
  field('Encrypted Size',   formatBytes(vault.encryptedSizeBytes));
  field('Registration Date', new Date(vault.createdAt).toLocaleString());

  // ── Identity Section ────────────────────────────────────────────────────────
  sectionDivider('IDENTITY & SECURITY');
  field('DNA Record ID', vault.dnaRecordId);
  field('Vault ID',      vault.id);
  field('Encryption',    `${vault.encryptionAlgorithm} · ${vault.keyDerivation}`);
  field('DNA Layers',    '6 layers · SHA-256, Structural, Perceptual, Semantic, Metadata, HMAC');

  // ── Legal Statement ─────────────────────────────────────────────────────────
  y += 4;
  doc.setFontSize(8); doc.setTextColor(140); doc.setFont('helvetica', 'normal');
  const ownerLabel = user?.name ?? user?.shortId ?? 'the registered owner';
  const stmt =
    `This certificate confirms that the file "${vault.originalFileName}" was registered ` +
    `in the PINIT-DNA system on ${new Date(vault.createdAt).toLocaleDateString()} ` +
    `by ${ownerLabel} (User ID: ${user?.sub ?? 'unknown'}). ` +
    `The file has been cryptographically fingerprinted across 10 independent layers ` +
    `and securely stored with AES-256-GCM encryption. ` +
    `This certificate was generated on ${new Date().toLocaleDateString()}.`;
  const stmtLines = doc.splitTextToSize(stmt, W - MARGIN * 2);
  doc.text(stmtLines, MARGIN, y);

  // Footer
  doc.setFontSize(8); doc.setTextColor(70);
  doc.text('PINIT-DNA Universal File DNA Engine v2.0', W / 2, 282, { align: 'center' });

  doc.save(`${certId}.pdf`);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function sectionHeader(doc: any, title: string, y: number) {
  doc.setFillColor(240, 242, 248);
  doc.rect(14, y - 1, 182, 7, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 41, 59);
  doc.text(title, 16, y + 4);
}

function downloadJSON(obj: object, filename: string) {
  const blob = new Blob([JSON.stringify(obj, null, 2)], { type: 'application/json' });
  download(blob, filename);
}

function downloadText(text: string, filename: string, mime = 'text/plain') {
  download(new Blob([text], { type: mime }), filename);
}

function download(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
