/**
 * Central feature keys for entitlement checks.
 * Never scatter string literals — always import from here.
 */

export const FeatureKey = {
  FEATURE_DNA: 'FEATURE_DNA',
  FEATURE_VAULT: 'FEATURE_VAULT',
  FEATURE_CERTIFICATES: 'FEATURE_CERTIFICATES',
  FEATURE_DASHBOARD: 'FEATURE_DASHBOARD',
  FEATURE_PROFILE: 'FEATURE_PROFILE',
  FEATURE_INVESTIGATION: 'FEATURE_INVESTIGATION',
  FEATURE_TRACKING: 'FEATURE_TRACKING',
  FEATURE_SMART_SHARE: 'FEATURE_SMART_SHARE',
  // Future-ready (not enforced in UI/routes yet except via plan maps)
  FEATURE_CHROME_EXTENSION: 'FEATURE_CHROME_EXTENSION',
  FEATURE_MARKETPLACE: 'FEATURE_MARKETPLACE',
  FEATURE_ASSET_LICENSING: 'FEATURE_ASSET_LICENSING',
  FEATURE_SELLING_ASSETS: 'FEATURE_SELLING_ASSETS',
  FEATURE_ENTERPRISE_TEAMS: 'FEATURE_ENTERPRISE_TEAMS',
  FEATURE_API_ACCESS: 'FEATURE_API_ACCESS',
  FEATURE_BULK_UPLOAD: 'FEATURE_BULK_UPLOAD',
  FEATURE_AI_MONITORING: 'FEATURE_AI_MONITORING',
  FEATURE_ADVANCED_REPORTS: 'FEATURE_ADVANCED_REPORTS',
} as const;

export type FeatureKey = (typeof FeatureKey)[keyof typeof FeatureKey];

export const PREMIUM_FEATURES: FeatureKey[] = [
  FeatureKey.FEATURE_INVESTIGATION,
  FeatureKey.FEATURE_TRACKING,
  FeatureKey.FEATURE_SMART_SHARE,
  FeatureKey.FEATURE_CHROME_EXTENSION,
  FeatureKey.FEATURE_MARKETPLACE,
  FeatureKey.FEATURE_ASSET_LICENSING,
  FeatureKey.FEATURE_SELLING_ASSETS,
  FeatureKey.FEATURE_ENTERPRISE_TEAMS,
  FeatureKey.FEATURE_API_ACCESS,
  FeatureKey.FEATURE_BULK_UPLOAD,
  FeatureKey.FEATURE_AI_MONITORING,
  FeatureKey.FEATURE_ADVANCED_REPORTS,
];
