import {
  ArrowUpRight,
  Baseline,
  BarChart3,
  Boxes,
  Brain,
  Building,
  Building2,
  Camera,
  Code2,
  Coins,
  Compass,
  Copy,
  Cpu,
  DollarSign,
  Facebook,
  FileWarning,
  Fingerprint,
  FolderKanban,
  FolderTree,
  Gauge,
  Github,
  Globe2,
  GraduationCap,
  Instagram,
  Landmark,
  Layers,
  Layers3,
  Linkedin,
  Lock,
  Map,
  Megaphone,
  Music,
  Package,
  Palette,
  PenLine,
  PenTool,
  Puzzle,
  Radar,
  Radio,
  Rocket,
  ScanFace,
  ScrollText,
  Search,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Stethoscope,
  TrendingDown,
  TrendingUp,
  Twitter,
  Users,
  Users2,
  Video,
  Wallet,
  Youtube,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * Icons are stored in the database as strings, so the admin panel can pick one
 * without the page importing every icon in the library. Only names in this map
 * are selectable — an unknown name falls back to `Sparkles` rather than crashing
 * the render.
 */
export const ICONS = {
  ArrowUpRight,
  Baseline,
  BarChart3,
  Boxes,
  Brain,
  Building,
  Building2,
  Camera,
  Code2,
  Coins,
  Compass,
  Copy,
  Cpu,
  DollarSign,
  Facebook,
  FileWarning,
  Fingerprint,
  FolderKanban,
  FolderTree,
  Gauge,
  Github,
  Globe2,
  GraduationCap,
  Instagram,
  Landmark,
  Layers,
  Layers3,
  Linkedin,
  Lock,
  Map,
  Megaphone,
  Music,
  Package,
  Palette,
  PenLine,
  PenTool,
  Puzzle,
  Radar,
  Radio,
  Rocket,
  ScanFace,
  ScrollText,
  Search,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Stethoscope,
  TrendingDown,
  TrendingUp,
  Twitter,
  Users,
  Users2,
  Video,
  Wallet,
  Youtube,
  Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export const ICON_NAMES = Object.keys(ICONS) as IconName[];

/** Resolve a stored icon name to a component, never throwing on bad data. */
export function icon(name: string | null | undefined): LucideIcon {
  return (ICONS as Record<string, LucideIcon>)[name ?? ''] ?? Sparkles;
}
